// <auto-generated />
using System;
using FInd_Op_Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FInd_Op_Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610044829_UpdateKYCAndFeedbacks")]
    partial class UpdateKYCAndFeedbacks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FInd_Op_Web.Models.AdBoost", b =>
                {
                    b.Property<int>("BoostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoostId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("BoostEndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("BoostStartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("BoostedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsPriority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int?>("RecruitmentAdId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("BoostId");

                    b.HasIndex("BoostedByUserId");

                    b.HasIndex("PostId");

                    b.HasIndex("RecruitmentAdId");

                    b.ToTable("AdBoosts");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.BookingCommission", b =>
                {
                    b.Property<int>("CommissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommissionId"));

                    b.Property<decimal>("BookingAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsPaidToPlatform")
                        .HasColumnType("bit");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("StadiumOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("CommissionId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("StadiumOwnerId");

                    b.ToTable("BookingCommissions");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.DirectMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("DirectMessages");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.JoinRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("JoinRequests");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MatchID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<bool?>("AwayConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("int")
                        .HasColumnName("AwayTeamID");

                    b.Property<string>("BookingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CancelRequestedBy")
                        .HasColumnType("int")
                        .HasColumnName("CancelRequestedBy");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<bool?>("HomeConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("int")
                        .HasColumnName("HomeTeamID");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatchStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatchType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Friendly");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultVisibility")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Public");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    b.Property<int?>("SportId")
                        .HasColumnType("int")
                        .HasColumnName("SportId");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("int");

                    b.Property<string>("TournamentStage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MatchId")
                        .HasName("PK__Matches__4218C8373268C8E4");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CancelRequestedBy");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SportId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.MatchChat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatId"));

                    b.Property<string>("EncryptedMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("SenderTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ChatId");

                    b.HasIndex("MatchId");

                    b.HasIndex("SenderTeamId");

                    b.ToTable("MatchChats");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.MatchPoll", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("MatchID");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("PlayerID");

                    b.Property<bool?>("IsAttending")
                        .HasColumnType("bit");

                    b.HasKey("MatchId", "PlayerId")
                        .HasName("PK__MatchPol__D6BC2F7D6D6D5E38");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchPolls");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.MatchRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestingTeamId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequestId");

                    b.HasIndex("MatchId");

                    b.HasIndex("RequestingTeamId");

                    b.ToTable("MatchRequests");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.MediaFile", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MediaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("EntityID");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MediaId")
                        .HasName("PK__MediaFil__B2C2B5AF86BF5F03");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E32935404C6");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Premium");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Pitch", b =>
                {
                    b.Property<int>("PitchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PitchID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PitchId"));

                    b.Property<string>("GrassType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PitchName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PitchSize")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SportId")
                        .HasColumnType("int")
                        .HasColumnName("SportId");

                    b.Property<int?>("StadiumId")
                        .HasColumnType("int")
                        .HasColumnName("StadiumID");

                    b.HasKey("PitchId")
                        .HasName("PK__Pitches__B68228186D58E2AE");

                    b.HasIndex("SportId");

                    b.HasIndex("StadiumId");

                    b.ToTable("Pitches");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.PitchSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int?>("BookedById")
                        .HasColumnType("int")
                        .HasColumnName("BookedByID");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PitchId")
                        .HasColumnType("int")
                        .HasColumnName("PitchID");

                    b.Property<int?>("RecurringId")
                        .HasColumnType("int")
                        .HasColumnName("RecurringID");

                    b.Property<string>("ScheduleStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Confirmed");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.HasKey("ScheduleId")
                        .HasName("PK__PitchSch__9C8A5B694BB6F176");

                    b.HasIndex("BookedById");

                    b.HasIndex("PitchId");

                    b.HasIndex("RecurringId");

                    b.ToTable("PitchSchedules");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.PlayerRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RatedById")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RatedById");

                    b.HasIndex("TeamId");

                    b.ToTable("PlayerRatings");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.PlayerSportProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("PreferredPosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("RatingScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("SkillLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SportId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalMatches")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ProfileId")
                        .HasName("PK__PlayerSportProfile");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SportId");

                    b.ToTable("PlayerSportProfiles");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PostId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.RecruitmentAd", b =>
                {
                    b.Property<int>("AdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdId"));

                    b.Property<DateTime?>("BoostUntil")
                        .HasColumnType("datetime");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBoosted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("MatchID");

                    b.Property<string>("PositionNeeded")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SportId")
                        .HasColumnType("int")
                        .HasColumnName("SportId");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AdId")
                        .HasName("PK__Recruitm__7130D58EB18579EB");

                    b.HasIndex("MatchId");

                    b.HasIndex("SportId");

                    b.HasIndex("TeamId");

                    b.ToTable("RecruitmentAds");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.RecurringBooking", b =>
                {
                    b.Property<int>("RecurringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecurringID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecurringId"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("PitchId")
                        .HasColumnType("int")
                        .HasColumnName("PitchID");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.HasKey("RecurringId")
                        .HasName("PK__Recurrin__738186825283E687");

                    b.HasIndex("PitchId");

                    b.HasIndex("TeamId");

                    b.ToTable("RecurringBookings");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A9A190F1D");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B61607CAA59C5")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Sport", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SportId");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Stadium", b =>
                {
                    b.Property<int>("StadiumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StadiumID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StadiumId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BankAccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hotline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("OwnerID");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StadiumName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StadiumId")
                        .HasName("PK__Stadiums__ED833038C8DC0ECE");

                    b.HasIndex("OwnerId");

                    b.ToTable("Stadiums");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.SystemInvoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StadiumOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPayableToOwner")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId");

                    b.HasIndex("StadiumOwnerId");

                    b.ToTable("SystemInvoices");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int?>("CaptainId")
                        .HasColumnType("int")
                        .HasColumnName("CaptainID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FoundedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("FundBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeArea")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsDisbanded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsFundUnlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSubscriptionActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("LookingForOpponent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("QualityLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RankingScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1000);

                    b.Property<string>("RankingTier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SportId")
                        .HasColumnType("int")
                        .HasColumnName("SportId");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeamId")
                        .HasName("PK__Teams__123AE7B988944AE2");

                    b.HasIndex("CaptainId");

                    b.HasIndex("SportId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TeamFundTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamFundTransactions");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TeamMember", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("PlayerID");

                    b.Property<DateTime?>("JoinedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RoleInTeam")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Member");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.HasKey("TeamId", "PlayerId")
                        .HasName("PK__TeamMemb__869E00F323A341A2");

                    b.HasIndex("PlayerId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TeamRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("RatedTeamId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerTeamId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("MatchId");

                    b.HasIndex("RatedTeamId");

                    b.HasIndex("ReviewerTeamId");

                    b.ToTable("TeamRatings");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TeamSubscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("PaidByUserId")
                        .HasColumnType("int");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Basic");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("PaidByUserId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamSubscriptions");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TokenTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("TokenTransactions");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("EntryFee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Format")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsFeePaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MaxPlayersPerTeam")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<int?>("SportId")
                        .HasColumnType("int");

                    b.Property<int?>("StadiumId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Upcoming");

                    b.Property<string>("TournamentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TournamentId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("SportId");

                    b.HasIndex("StadiumId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TournamentFee", b =>
                {
                    b.Property<int>("FeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PaidByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("FeeId");

                    b.HasIndex("PaidByUserId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentFees");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TournamentTeam", b =>
                {
                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<bool>("NoBettingCommitment")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TeamAbbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TournamentId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("TournamentTeams");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TournamentTeamPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentTeamPlayers");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdCardBackUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdCardFrontUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFreeAgent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("KycStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PremiumUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tokens")
                        .HasColumnType("int");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC4609C301");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E42A2264E0")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.WithdrawalRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StadiumOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequestId");

                    b.HasIndex("StadiumOwnerId");

                    b.ToTable("WithdrawalRequests");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK__UserRole__AF27604FE3C98EF0");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("FInd_Op_Web.Models.AdBoost", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "BoostedByUser")
                        .WithMany()
                        .HasForeignKey("BoostedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FInd_Op_Web.Models.RecruitmentAd", "RecruitmentAd")
                        .WithMany()
                        .HasForeignKey("RecruitmentAdId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BoostedByUser");

                    b.Navigation("Post");

                    b.Navigation("RecruitmentAd");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.BookingCommission", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.PitchSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.User", "StadiumOwner")
                        .WithMany()
                        .HasForeignKey("StadiumOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("StadiumOwner");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.DirectMessage", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Feedback", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.JoinRequest", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Match", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.Team", "AwayTeam")
                        .WithMany("MatchAwayTeams")
                        .HasForeignKey("AwayTeamId")
                        .HasConstraintName("FK__Matches__AwayTea__6383C8BA");

                    b.HasOne("FInd_Op_Web.Models.Team", "CancelRequestedByNavigation")
                        .WithMany("MatchCancelRequestedByNavigations")
                        .HasForeignKey("CancelRequestedBy")
                        .HasConstraintName("FK__Matches__CancelR__656C112C");

                    b.HasOne("FInd_Op_Web.Models.Team", "HomeTeam")
                        .WithMany("MatchHomeTeams")
                        .HasForeignKey("HomeTeamId")
                        .HasConstraintName("FK__Matches__HomeTea__628FA481");

                    b.HasOne("FInd_Op_Web.Models.PitchSchedule", "Schedule")
                        .WithMany("Matches")
                        .HasForeignKey("ScheduleId")
                        .HasConstraintName("FK__Matches__Schedul__6477ECF3");

                    b.HasOne("FInd_Op_Web.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId");

                    b.HasOne("FInd_Op_Web.Models.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AwayTeam");

                    b.Navigation("CancelRequestedByNavigation");

                    b.Navigation("HomeTeam");

                    b.Navigation("Schedule");

                    b.Navigation("Sport");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.MatchChat", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.Team", "SenderTeam")
                        .WithMany()
                        .HasForeignKey("SenderTeamId")
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("SenderTeam");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.MatchPoll", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.Match", "Match")
                        .WithMany("MatchPolls")
                        .HasForeignKey("MatchId")
                        .IsRequired()
                        .HasConstraintName("FK__MatchPoll__Match__66603565");

                    b.HasOne("FInd_Op_Web.Models.User", "Player")
                        .WithMany("MatchPolls")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK__MatchPoll__Playe__6754599E");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.MatchRequest", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.Team", "RequestingTeam")
                        .WithMany()
                        .HasForeignKey("RequestingTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("RequestingTeam");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Notification", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Notificat__UserI__6FE99F9F");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.PaymentTransaction", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Pitch", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId");

                    b.HasOne("FInd_Op_Web.Models.Stadium", "Stadium")
                        .WithMany("Pitches")
                        .HasForeignKey("StadiumId")
                        .HasConstraintName("FK__Pitches__Stadium__5165187F");

                    b.Navigation("Sport");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.PitchSchedule", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "BookedBy")
                        .WithMany("PitchSchedules")
                        .HasForeignKey("BookedById")
                        .HasConstraintName("FK__PitchSche__Booke__5BE2A6F2");

                    b.HasOne("FInd_Op_Web.Models.Pitch", "Pitch")
                        .WithMany("PitchSchedules")
                        .HasForeignKey("PitchId")
                        .HasConstraintName("FK__PitchSche__Pitch__5AEE82B9");

                    b.HasOne("FInd_Op_Web.Models.RecurringBooking", "Recurring")
                        .WithMany("PitchSchedules")
                        .HasForeignKey("RecurringId")
                        .HasConstraintName("FK__PitchSche__Recur__5CD6CB2B");

                    b.Navigation("BookedBy");

                    b.Navigation("Pitch");

                    b.Navigation("Recurring");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.PlayerRating", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.User", "RatedBy")
                        .WithMany()
                        .HasForeignKey("RatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("RatedBy");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.PlayerSportProfile", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("FK_PlayerSportProfile_Users");

                    b.HasOne("FInd_Op_Web.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .HasConstraintName("FK_PlayerSportProfile_Sports");

                    b.Navigation("Player");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Post", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FInd_Op_Web.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.RecruitmentAd", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.Match", "Match")
                        .WithMany("RecruitmentAds")
                        .HasForeignKey("MatchId")
                        .HasConstraintName("FK__Recruitme__Match__6EF57B66");

                    b.HasOne("FInd_Op_Web.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId");

                    b.HasOne("FInd_Op_Web.Models.Team", "Team")
                        .WithMany("RecruitmentAds")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__Recruitme__TeamI__6E01572D");

                    b.Navigation("Match");

                    b.Navigation("Sport");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.RecurringBooking", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.Pitch", "Pitch")
                        .WithMany("RecurringBookings")
                        .HasForeignKey("PitchId")
                        .HasConstraintName("FK__Recurring__Pitch__5629CD9C");

                    b.HasOne("FInd_Op_Web.Models.Team", "Team")
                        .WithMany("RecurringBookings")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__Recurring__TeamI__571DF1D5");

                    b.Navigation("Pitch");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Stadium", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "Owner")
                        .WithMany("Stadia")
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("FK__Stadiums__OwnerI__4E88ABD4");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.SystemInvoice", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "StadiumOwner")
                        .WithMany()
                        .HasForeignKey("StadiumOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StadiumOwner");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Team", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "Captain")
                        .WithMany("Teams")
                        .HasForeignKey("CaptainId")
                        .HasConstraintName("FK__Teams__CaptainID__44FF419A");

                    b.HasOne("FInd_Op_Web.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId");

                    b.Navigation("Captain");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TeamFundTransaction", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("FInd_Op_Web.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TeamMember", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "Player")
                        .WithMany("TeamMembers")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK__TeamMembe__Playe__48CFD27E");

                    b.HasOne("FInd_Op_Web.Models.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .IsRequired()
                        .HasConstraintName("FK__TeamMembe__TeamI__47DBAE45");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TeamRating", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.Team", "RatedTeam")
                        .WithMany("RatedTeamRatings")
                        .HasForeignKey("RatedTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.Team", "ReviewerTeam")
                        .WithMany("ReviewerTeamRatings")
                        .HasForeignKey("ReviewerTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("RatedTeam");

                    b.Navigation("ReviewerTeam");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TeamSubscription", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "PaidByUser")
                        .WithMany()
                        .HasForeignKey("PaidByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaidByUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TokenTransaction", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Tournament", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FInd_Op_Web.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId");

                    b.HasOne("FInd_Op_Web.Models.Stadium", "Stadium")
                        .WithMany()
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organizer");

                    b.Navigation("Sport");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TournamentFee", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "PaidByUser")
                        .WithMany()
                        .HasForeignKey("PaidByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaidByUser");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TournamentTeam", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.Team", "Team")
                        .WithMany("TournamentTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.Tournament", "Tournament")
                        .WithMany("TournamentTeams")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.TournamentTeamPlayer", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FInd_Op_Web.Models.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.WithdrawalRequest", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.User", "StadiumOwner")
                        .WithMany()
                        .HasForeignKey("StadiumOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StadiumOwner");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("FInd_Op_Web.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__RoleI__403A8C7D");

                    b.HasOne("FInd_Op_Web.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__UserI__3F466844");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Match", b =>
                {
                    b.Navigation("MatchPolls");

                    b.Navigation("RecruitmentAds");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Pitch", b =>
                {
                    b.Navigation("PitchSchedules");

                    b.Navigation("RecurringBookings");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.PitchSchedule", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.RecurringBooking", b =>
                {
                    b.Navigation("PitchSchedules");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Stadium", b =>
                {
                    b.Navigation("Pitches");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Team", b =>
                {
                    b.Navigation("MatchAwayTeams");

                    b.Navigation("MatchCancelRequestedByNavigations");

                    b.Navigation("MatchHomeTeams");

                    b.Navigation("RatedTeamRatings");

                    b.Navigation("RecruitmentAds");

                    b.Navigation("RecurringBookings");

                    b.Navigation("ReviewerTeamRatings");

                    b.Navigation("TeamMembers");

                    b.Navigation("TournamentTeams");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.Tournament", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("TournamentTeams");
                });

            modelBuilder.Entity("FInd_Op_Web.Models.User", b =>
                {
                    b.Navigation("MatchPolls");

                    b.Navigation("Notifications");

                    b.Navigation("PitchSchedules");

                    b.Navigation("Stadia");

                    b.Navigation("TeamMembers");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
