const fs = require('fs');

function fixFile(file) {
  let text = fs.readFileSync(file, 'utf8');

  const map = {
    'Ä á»™i': 'Đội',
    'Ä‘á»™i': 'đội',
    'báº¡n': 'bạn',
    'yÃªu cáº§u': 'yêu cầu',
    'giao há»¯u': 'giao hữu',
    'tráº­n Ä‘áº¥u': 'trận đấu',
    'Ná»™i bá»™': 'Nội bộ',
    'khÃ´ng': 'không',
    'thÃ nh cÃ´ng': 'thành công',
    'bá»‹': 'bị',
    'Ä‘Ã£': 'đã',
    'Báº¡n': 'Bạn',
    'tá»‘i Ä‘a': 'tối đa',
    'thá»ƒ thao': 'thể thao',
    'mÃ´n': 'môn',
    'rá»“i': 'rồi',
    'Táº¡o': 'Tạo',
    'bÃ³ng': 'bóng',
    'Cáº­p nháº­t': 'Cập nhật',
    'thÃ´ng tin': 'thông tin',
    'cáº§n': 'cần',
    'táº¡o': 'tạo',
    'trÆ°á»›c khi': 'trước khi',
    'Ä Äƒng bÃ i': 'Đăng bài',
    'dÃ¹ng háº¿t': 'dùng hết',
    'lÆ°á»£t': 'lượt',
    'TÃ¬m Ä á»‘i/NgÆ°á» i': 'Tìm Đối/Người',
    'miá»…n phÃ­': 'miễn phí',
    'trong thÃ¡ng nÃ y': 'trong tháng này',
    'Vui lÃ²ng': 'Vui lòng',
    'nÃ¢ng cáº¥p': 'nâng cấp',
    'NhÃ ': 'Nhà',
    'KhÃ¡ch': 'Khách',
    'sÃ¢n': 'sân',
    'ngoÃ i': 'ngoài',
    'TÃ­nh Ä‘iá»ƒm': 'Tính điểm',
    'nÃ¢ng cao': 'nâng cao',
    'Lá»‡ch báº­c': 'Lệch bậc',
    'há»§y': 'hủy',
    'bá»Ÿi': 'bởi',
    'LÃ½ do': 'Lý do',
    'lá»‹ch Ä‘áº·t': 'lịch đặt',
    'vÃ´ hiá»‡u hÃ³a': 'vô hiệu hóa',
    'ThÃ¡ch Ä‘áº¥u': 'Thách đấu',
    'Ä Ã¢y': 'Đây',
    'pháº£i lÃ ': 'phải là',
    'tá»± do': 'tự do',
    'KÃ¨o': 'Kèo',
    'Ä‘Æ°á»£c': 'được',
    'nháº­n': 'nhận',
    'thÃ¡ch Ä‘áº¥u': 'thách đấu',
    'cá»§a': 'của',
    'CÆ¡ cháº¿': 'Cơ chế',
    'SÃ¢n dá»± kiáº¿n': 'Sân dự kiến',
    'giáº£i': 'giải',
    'BÃ³ng Ä‘Ã¡': 'Bóng đá',
    'duyá»‡t': 'duyệt',
    'vÃ o': 'vào',
    'tá»« chá»‘i': 'từ chối',
    'vÃ ': 'và',
    'xÃ³a': 'xóa',
    'cÃ³': 'có',
    'Ä‘Äƒng kÃ½': 'đăng ký',
    'thá»ƒ': 'thể',
    'tá»±': 'tự',
    'cam káº¿t': 'cam kết',
    'chÆ¡i': 'chơi',
    'cÃ¡ Ä‘á»™': 'cá độ',
    'nÃ y': 'này',
    'KhÃ´ng tÃ¬m tháº¥y': 'Không tìm thấy',
    'hoáº·c': 'hoặc',
    'quyá» n': 'quyền',
    'Chá»‰ Ã¡p dá»¥ng': 'Chỉ áp dụng',
    'cho': 'cho',
    'XÃ³a': 'Xóa',
    'cÃ¡c': 'các',
    'cÅ©': 'cũ',
    'náº¿u': 'nếu',
    'chia': 'chia',
    'luÃ´n': 'luôn',
    'áº£o': 'ảo',
    'táº¡m lÃ m': 'tạm làm',
    'quáº£n lÃ½': 'quản lý',
    'GÃ¡n': 'Gán',
    'cáº§u thá»§': 'cầu thủ',
    'NgÆ°á» i': 'Người',
    'Ä‘áº§u tiÃªn': 'đầu tiên',
    'lÃ m': 'làm',
    'Ä‘á»™i trÆ°á»Ÿng': 'đội trưởng',
    'Ä‘á»•i tÃªn': 'đổi tên',
    'hiá»‡n táº¡i': 'hiện tại',
    'chÆ°a diá»…n ra': 'chưa diễn ra',
    'HÃ m Ä‘á»‡ quy': 'Hàm đệ quy',
    'tÃ¬m táº¥t cáº£': 'tìm tất cả',
    'LÆ°u': 'Lưu',
    'sÆ¡ Ä‘á»“': 'sơ đồ',
    'nhÃ¡nh': 'nhánh',
    'gá»­i': 'gửi',
    'báº¯t kÃ¨o': 'bắt kèo',
    'vá»«a': 'vừa',
    'vá»›i': 'với'
  };

  let newText = text;
  for (const [k, v] of Object.entries(map)) {
    newText = newText.split(k).join(v);
  }
  fs.writeFileSync(file, newText, 'utf8');
  console.log('Fixed', file);
}

fixFile('Controllers/CaptainController.cs');
fixFile('Controllers/PaymentController.cs');
fixFile('Controllers/StadiumOwnerController.cs');
